name: Create release in github

description: Create a release to git (version checking is handled by the calling workflow)

inputs:
  GITHUB_TOKEN:
    description: "GitHub token"
    required: true
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Get version
      id: get-version
      uses: ./.github/actions/get-current-version

    - name: Create release
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        TAG: ${{ steps.get-version.outputs.version }}
      run: |
        echo "Creating release for version $TAG"
        gh release create "$TAG" --title="v$TAG" --generate-notes
