name: Migrate database

description: "Migrate the database to the version given by git ref"

inputs:
  AZURE_CLIENT_ID:
    description: "Client ID for the service principal"
    required: true
  AZURE_TENANT_ID:
    description: "Tenant ID for the service principal"
    required: true
  AZURE_SUBSCRIPTION_ID:
    description: "Subscription ID for the service principal"
    required: true
  AZURE_ENVIRONMENT_KEY_VAULT_NAME:
    description: "Name of the key vault"
    required: true
  AZURE_NAME_PREFIX:
    description: "Prefix for all resources"
    required: true
  MIGRATION_DOCKER_IMAGE_BASE_NAME:
    description: "Base name for the migration image (e.g. ghcr.io/altinn/altinn-broker-migration)"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Checkout repository"
      uses: actions/checkout@v4

    - name: Get version
      id: get-version
      uses: ./.github/actions/get-current-version

    - name: OIDC Login to Azure Public Cloud
      uses: azure/login@v2
      with:
        client-id: ${{ inputs.AZURE_CLIENT_ID }}
        tenant-id: ${{ inputs.AZURE_TENANT_ID }}
        subscription-id: ${{ inputs.AZURE_SUBSCRIPTION_ID }}

    - name: Publish migration image
      uses: ./.github/actions/publish-image
      with:
        dockerImageBaseName: ${{ inputs.MIGRATION_DOCKER_IMAGE_BASE_NAME }}
        imageTag: ${{ steps.get-version.outputs.imageTag }}
        GITHUB_TOKEN: ${{ github.token }}
        dockerfile: Dockerfile.migration

    - name: Set MIGRATION_IMAGE environment variable
      shell: bash
      run: |
        echo "MIGRATION_IMAGE=${{ inputs.MIGRATION_DOCKER_IMAGE_BASE_NAME }}:${{ steps.get-version.outputs.imageTag }}" >> "$GITHUB_ENV"

    - name: Deploy migration job
      uses: azure/arm-deploy@v2
      id: migration-job
      env:
        KEY_VAULT_NAME: ${{ inputs.AZURE_ENVIRONMENT_KEY_VAULT_NAME }}
        KEY_VAULT_URL: https://${{ inputs.AZURE_ENVIRONMENT_KEY_VAULT_NAME }}.vault.azure.net
        NAME_PREFIX: ${{ inputs.AZURE_NAME_PREFIX }}
        APP_VERSION: ${{ steps.get-version.outputs.imageTag }}
      with:
        scope: resourcegroup
        template: ./.azure/applications/migration/main.bicep
        resourceGroupName: ${{ inputs.AZURE_NAME_PREFIX }}-rg
        deploymentMode: Incremental
        deploymentName: migration-${{ steps.get-version.outputs.imageTag }}
        region: norwayeast
        failOnStdErr: false
        parameters: ./.azure/applications/migration/params.bicepparam

    - name: Start migration job
      uses: azure/CLI@v2
      with:
        azcliversion: 2.72.0
        inlineScript: |
          az containerapp job start -n ${{ steps.migration-job.outputs.name }} -g ${{ inputs.AZURE_NAME_PREFIX }}-rg

    - name: Verify migration
      uses: azure/CLI@v2
      id: verify-migration
      with:
        azcliversion: 2.72.0
        inlineScript: |
          chmod +x ./.github/tools/containerAppJobVerifier.sh
          ./.github/tools/containerAppJobVerifier.sh ${{ steps.migration-job.outputs.name }} '${{ inputs.AZURE_NAME_PREFIX }}-rg' ${{ steps.get-version.outputs.imageTag }}

    - name: Logout from azure
      shell: bash
      if: ${{failure() || success()}}
      continue-on-error: true
      run: az logout
