changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes 🛠
      labels:
        - kind/breaking-change
    - title: New Features 🎉
      labels:
        - kind/feature
    - title: Bugfixes 🐛
      labels:
        - kind/bug
    - title: Other Changes
      labels:
        - kind/other
    - title: Dependency Upgrades 📦
      labels:
        - kind/dependencies
    - title: Incident
      labels:
        - kind/incident
    - title: Uncategorized changes
      labels:
        - "*"
