version: '3.4'

volumes:
    broker-storage:

networks:
  altinnplatform_network:
    external: false

services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"
      - "10001:10001"
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: broker
  broker-flyway-local:
    image: flyway/flyway@sha256:16f25b55404b0d1ca8a4236d522d47793f503a531b7312351cf065ee0fa1a89b
    command: -url='jdbc:postgresql://database:5432/broker' -user=postgres -password=postgres -connectRetries=60 migrate -validateMigrationNaming='true'
    volumes:
      - ./src/Altinn.Broker.Persistence/Migrations:/flyway/sql
    depends_on:
      - database
    entrypoint:
      [
        "flyway",
      ]
