version: '3.4'

services:
  k6-test:
    image: grafana/k6:latest
    command: run /test.js
    volumes:
      - ./Test/Altinn.Broker.Tests/K6.Tests/test.js:/test.js
      - ./Test/Altinn.Broker.Tests/K6.Tests/data:/data
