name: Publish image

description: "Publishes a docker image to GitHub Container Registry"

inputs:
  dockerImageBaseName:
    description: "Base image name for docker images"
    required: true
  imageTag:
    description: "Tag for the image"
    required: true
  GITHUB_TOKEN:
    description: "GitHub token"
    required: true
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v6
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.GITHUB_TOKEN }}

    - name: Push image to registry
      shell: bash
      run: |
        # Construct the image tag using the Git hash
        IMAGE="${{ inputs.dockerImageBaseName }}:${{ inputs.imageTag }}"
        docker build . --tag $IMAGE
        docker push $IMAGE
