name: Epic 💎
description: Create a new epic based on user and vendor views
labels: ["kind/epic", "status/draft"]
body:          
  - type: markdown
    attributes:
      value: "## Users View"

  - type: textarea
    id: users-view
    attributes:
      label: Title, User role(s), and Users value statement(s)
      description: Provide the title, user role(s), and value statement(s) from the user's perspective.
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Vendors View"

  - type: textarea
    id: vendors-view-description
    attributes:
      label: Description
      description: High level features (capabilities) and additional information from the vendor's perspective.

  - type: markdown
    attributes:
      value: "```[tasklist]\n### Features\n```"

  - type: markdown
    attributes:
      value: "```[tasklist]\n### Work items"

  - type: textarea
    id: work-items-tasklist
    attributes:
      label: List of Work Items
      description: Provide the list of work items to be considered for this epic.

  - type: markdown
    attributes:
      value: "## Item Attributes"

  - type: textarea
    id: item-attributes
    attributes:
      label: Automatically updated properties
      description: Provide the automatically updated properties related to this epic.

  - type: markdown
    attributes:
      value: |
        * Check the [Definition of Ready](https://docs.altinn.studio/community/devops/definition-of-ready/) if you need hints on what to include.
        * Remember to link all relevant issues (bugs, user stories, chores)
