name: Check formatting
on:
  workflow_call:
  workflow_dispatch:
jobs:
  check-formatting:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Altinn Broker Repository"
        uses: actions/checkout@v4
        with:
          repository: "Altinn/altinn-broker"
          submodules: true  # or 'recursive' for recursive submodules
          ref: 'main'

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x

      - name: Format
        run: |
          dotnet format --verify-no-changes --verbosity diagnostic --include ./src/**
