name: Formatting
on:
  workflow_dispatch:
  workflow_call:

jobs:
  check-formatting:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4

        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
           dotnet-version: |
            8.0.x

        - name: Format
          run: |
            dotnet format --verify-no-changes --verbosity diagnostic --include ./src/**
