name: .NET Analysis
on:
  workflow_call:
  workflow_dispatch:
jobs:
  build-test-analyze:
    name: Build, test & analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x

      - name: Start dependencies for tests (docker-compose)
        run: |
          docker-compose up -d

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test --no-build --configuration Release