name: .NET Analysis
on:
  workflow_call:
  workflow_dispatch:
jobs:
  build-test-analyze:
    name: Build, test & analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x

      - name: Format
        run: |
          dotnet format Altinn.Broker.sln --verify-no-changes --verbosity diagnostic  --include ./src/**

      - name: Start dependencies for tests (docker-compose)
        run: |
          docker-compose up -d

      - name: Build & Test
        run: |
          dotnet build Altinn.Broker.sln -v q

          dotnet test Altinn.Broker.sln \
          -v q \
          --collect:"XPlat Code Coverage" \
          --results-directory TestResults/ \
          --logger "trx;" \
          --configuration release \
          -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover

      - name: Process .NET test result
        if: ${{ failure() }}
        uses: NasAmin/trx-parser@v0.6.0
        with:
          TRX_PATH: ${{ github.workspace }}/TestResults
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
