name: "Check for file changes"

on:
  workflow_call:
    outputs:
      hasAzureChanges:
        description: "Azure related files changed"
        value: ${{ jobs.check-for-changes.outputs.hasAzureChanges }}
      hasBackendChanges:
        description: "Backend related files changed"
        value: ${{ jobs.check-for-changes.outputs.hasBackendChanges }}
      hasMigrationChanges:
        description: "Migration related files changed"
        value: ${{ jobs.check-for-changes.outputs.hasMigrationChanges }}
jobs:
  check-for-changes:
    name: Filter
    runs-on: ubuntu-latest
    outputs:
      hasAzureChanges: ${{ steps.filter.outputs.azure_any_changed == 'true' }}
      hasBackendChanges: ${{ steps.filter.outputs.backend_any_changed == 'true' }}
      hasMigrationChanges : ${{ steps.filter.outputs.migration_any_changed == 'true' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # fetch-depth needs to be 0 in cases where we want to fetch changes since previous tag for example
          fetch-depth: 0

      - uses: tj-actions/changed-files@v42
        id: filter
        with:
          files_yaml: |
            azure:
              - '.github/**/*'
              - '.azure/infrastructure/**/*'
              - '.azure/modules/**/*'
            backend:
              - 'src/**/*'
            migrations: 
              - 'src/Altinn.Broker.Persistence/Migrations/*'
