name: Deploy solution

on:
  workflow_call:
    inputs:
      environment:
        type: string
      hasAzureChanges:
        type: string
      hasBackendChanges:
        type: string
      hasMigrationChanges:
        type: string
      imageTag:
        type: string
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - TEST
          - STAGING
          - PROD
      hasAzureChanges:
        description: Deploy infra
        type: boolean
      hasBackendChanges:
        description: Deploy app
        type: boolean
      hasMigrationChanges:
        description: Migrate database
        type: boolean
      imageTag:
        type: string

jobs:
  deploy-infra:
    name: Deploy infrastructure
    if: ${{ github.event.inputs.hasAzureChanges == 'true' }}
    uses: ./.github/workflows/action-deploy-infra.yml
    secrets: inherit
    with:
      region: norwayeast
      environment: test
      imageTag: ${{ github.event.inputs.imageTag }}
      ref: ${{ github.ref }}

  deploy-app:
    name: Deploy app to test
    needs:
      [
        deploy-infra, # we want deployment of app to be dependent on deployment of infrastructure, but if infrastructure is skipped, we still want to deploy the app
      ]
    if: ${{ github.event.inputs.hasBackendChanges == 'true' && always() && !failure() && !cancelled() }}
    uses: ./.github/workflows/action-deploy-app.yml
    secrets: inherit
    with:
      environment: test
      region: norwayeast
      ref: ${{ github.ref }}
      imageTag: ${{ github.event.inputs.imageTag }}
      migrate: ${{ github.event.inputs.hasMigrationChanges == 'true' }}
