name: "Generate git short sha"

on:
  workflow_call:
    outputs:
      gitShortSha:
        description: "Git short sha"
        value: ${{ jobs.generate-git-short-sha.outputs.gitShortSha }}
jobs:
  generate-git-short-sha:
    name: Generate git short sha
    runs-on: ubuntu-latest
    outputs:
      gitShortSha: ${{ steps.set-git-short-sha.outputs.gitShortSha }}
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4
      # Current workaround to create a short git sha. Not supported as a global variable yet. https://stackoverflow.com/questions/59810838/how-to-get-the-short-sha-for-the-github-workflow
      - name: Set git short sha
        id: set-git-short-sha
        run: echo "gitShortSha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
