name: Build and push
on:
  workflow_call:
    inputs:
      dockerImageBaseName:
        description: "Base image name for docker images"
        required: true
        type: string
      version:
        description: "Version to tag"
        required: true
        type: string

jobs:
  publish-docker-image:
    name: Build and push
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push image to registry
        run: |
          # Construct the image tag using the Git hash
          IMAGE_TAG="${{ inputs.dockerImageBaseName }}:${{ inputs.version }}"

          docker build . --tag $IMAGE_TAG
          docker push $IMAGE_TAG
