name: Checking label for PR
on:
  pull_request:
    types: [opened, reopened, ready_for_review, labeled, unlabeled]
jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: mheap/github-action-required-labels@v5
        with:
          mode: minimum
          count: 1
          labels: |
            kind/breaking-change
            kind/feature
            kind/feature-request
            kind/bug
            kind/other
            kind/user-story
            kind/dependencies
            kind/documentation
            kind/enhancement
            kind/incident
            kind/chore
