name: Test application

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches: [main]
    
jobs:
  test-application:
    name: Test application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x

      - name: Start dependencies for tests (docker compose)
        run: |
          docker compose up -d &   # Run in background and disown the process
          disown

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Wait for docker compose services to be ready and database migration to complete
        run: |
          timeout 5m bash -c '
            while ! docker ps | grep -q "(healthy)"; do
              echo "Waiting for services to be healthy..."
              sleep 5
            done
            while docker ps -a | grep -q "database_migration"; do
              if docker ps -a | grep -q "Exited.*database_migration"; then
                echo "Database migration completed."
                break
              fi
              echo "Waiting for database migration to complete..."
              sleep 5
            done
          '
      - name: Test
        run: dotnet test --no-build --configuration Release
